app:
  api:
    version: 2

swagger:
  api:
    info:
      title: Swagger x SpringBoot Sample API
      description:
        Spring Boot 2.x系での Swagger のサンプルです。
        詳細は下記リンクを参照してください。
        https://github.com/tkrplus/swagger-spring-boot