apiVersion: v1
kind: Service
metadata:
  name: swagger-spring-boot
spec:
  selector:
    app: swagger-spring-boot
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
